export const PROJECTS = [
  {
    title: "MERN E‑commerce Store",
    desc: "A full-stack commerce engine that synchronizes real-time product data using asynchronous API fetching.",
    tags: ["React", "Node", "Express", "MongoDB"],
    category: "APIs",
    image: "/daraz.png",
    link: "https://daraz-phi.vercel.app/",
  },
  {
    title: "Rental Property Management",
    desc: "A full-stack rental management system built to handle property listings and tenant records.",
    tags: ["React", "Node", "Express", "MongoDB"],
    category: "Full Stack",
    image: "/rental.png",
    link: "https://rental-management-front-end.vercel.app/",
  },
  {
    title: "News API",
    desc: "A RESTful News API that aggregates real-time headlines from multiple sources.",
    tags: ["Node", "Express", "MongoDB"],
    category: "APIs",
    image: "/news.png",
    link: "https://news-api-gray.vercel.app/",
  },
  {
    title: "VideoGrpah Template",
    desc: "A sleek, dark-themed responsive portfolio built with modern CSS.",
    tags: ["HTML", "CSS", "JS"],
    category: "Templates",
    image: "/videograph.png",
    link: "https://react-videograph.vercel.app/",
  },
  {
    title: "Acme Blog Template",
    desc: "A minimalist blog template with a focus on readability.",
    tags: ["JS", "HTML", "CSS", "React"],
    category: "Templates",
    image: "/acme.png",
    link: "https://acme-three-blue.vercel.app/",
  },
  {
    title: "Imagine Business Template",
    desc: "A professional business landing page template designed for startups.",
    tags: ["JS", "HTML", "CSS", "React"],
    category: "Templates",
    image: "/imagine.png",
    link: "https://imagine-repo.vercel.app/",
  },
];
